services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: nestjs_db
      POSTGRES_USER: nestjs_user
      POSTGRES_PASSWORD: nestjs_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://nestjs_user:nestjs_password@postgres:5432/nestjs_db

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: